### ISSUE TITLE
docs、imagesディレクトリの作成、CODE_OF_CONDUCT.mdの移行

### ISSUE THREAD

**Issue by pss-aileen** [first-contributions-ja/first-contributions-ja#18]
> docs/images
的なものがあっても良いのかなと思っていたりします。

確かにそうですね！
一旦docsフォルダを作ってみて、何かしら気になったらあとで変更する方向で良いと思いました！

そしたら、CODE OF CONDUCT.mdも、移行したほうがいいですね

_Originally posted by @kazzyfrog in https://github.com/first-contributions-ja/first-contributions-ja/discussions/16#discussioncomment-8759483_

---

タイトルの通り以下タスク

- [x] docsフォルダ作成
- [ ] docsの中にimagesフォルダ作成
- [x] rootにあるCODE_OF_CONDUCT.mdをdocsフォルダに移行する

**Comment by kagomen** [comment]
試しにやってみます！

**Comment by pss-aileen** [comment]
@kagomen 
mainブランチにdocsフォルダできちゃったので、mainブランチからブランチ作ってもらって作業してもらえれば良いかと思います！！
